### ISSUE TITLE
Similar but not identical Error in dmDSdata(counts = counts, samples = coldata) compare to  #1:

### ISSUE THREAD

**Issue by weir12** [nanoporetech/pipeline-transcriptome-de#3] opened 2019-03-05 12:52 UTC
Hi:
Hi Botond,I'm having an issue which is similar to #1 
But the error message is not exactly the same with that. Because my sample names has  letter prefixes.
Here are my **error messages**:
```
Make the TxDb object ... OK
Warning messages:
1: In .get_cds_IDX(type, phase) :
  The "phase" metadata column contains non-NA values for features of type
  stop_codon, exon. This information was ignored.
2: In .reject_transcripts(bad_tx, because) :
  The following transcripts were rejected because they have stop codons
  that cannot be mapped to an exon: AT1G07320.4, AT1G18180.2,
  AT1G30230.1, AT1G36380.1, AT1G52415.1, AT1G52940.1, AT2G18110.1,
  AT2G35130.1, AT2G35130.3, AT2G39050.1, AT3G13445.1, AT3G17660.1,
  AT3G17660.3, AT3G52070.2, AT3G54680.1, AT3G59450.2, AT4G13730.2,
  AT4G17730.1, AT4G39620.2, AT5G01520.2, AT5G22794.1, AT5G27710.2,
  AT5G45240.2
'select()' returned 1:many mapping between keys and columns
Filtering counts using DRIMSeq.
Error in dmDSdata(counts = counts, samples = coldata) : 
  mode(counts) %in% "numeric" is not TRUE
Calls: dmDSdata -> stopifnot
Execution halted
[Tue Mar  5 16:52:44 2019]
Error in rule de_analysis:
    jobid: 10
    output: de_analysis/results_dge.tsv, de_analysis/results_dge.pdf, de_analysis/results_dtu_gene.tsv, de_analysis/results_dtu_transcript.tsv, de_analysis/results_dtu_stageR.tsv, merged/all_counts_filtered.tsv, merged/all_gene_counts.tsv
    conda-env: /home/weir/output/Nanopore-DGE-Analysis/.snakemake/conda/589d7ca2

RuleException:
CalledProcessError in line 128 of /home/weir/software/pipeline-transcriptome-de/Snakefile:
Command 'source activate '/home/weir/output/Nanopore-DGE-Analysis/.snakemake/conda/589d7ca2'; set -euo pipefail;  /home/weir/software/pipeline-transcriptome-de/scripts/de_analysis.R' returned non-zero exit status 1.
  File "/home/weir/software/pipeline-transcriptome-de/Snakefile", line 128, in __rule_de_analysis
  File "/home/weir/anaconda3/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/weir/software/pipeline-transcriptome-de/.snakemake/log/2019-03-05T165022.384227.snakemake.log
```
Pasting the content of de_analysis/**coldata.tsv**
```
sample  condition       type
Col0_1  untreated       single-read
Col0_2  untreated       single-read
Col0_3  untreated       single-read
fip37_1 treated single-read
fip37_2 treated single-read
fip37_3 treated single-read
```
Pasting the head of merged/**all_counts.tsv**
```
Reference       Col0_1  Col0_2  Col0_3  fip37_1 fip37_2 fip37_3
AT1G67090.2     10935.0 15226.0 22425.0 15200.0 17476.0 16079.0
AT5G38410.3     5733.0  7984.0  12484.0 8362.0  9477.0  4255.0
AT1G29930.1     4225.0  6295.0  22283.0 10630.0 13423.0 24106.0
AT5G38420.1     3222.0  4647.0  1741.0  2569.0  3061.0  1424.0
AT5G38430.2     2826.0  4054.0  1496.0  1671.0  1875.0  1267.0
AT1G20340.1     2382.0  3245.0  5113.0  3062.0  3713.0  2819.0
AT1G79040.1     2155.0  2983.0  6866.0  3192.0  3861.0  4090.0
AT2G39730.3     1782.0  2725.0  3569.0  2003.0  2247.0  1826.0
AT5G54770.1     1770.0  2560.0  1898.0  1643.0  1996.0  1535.0
```
Pasting the content of de_analysis/**de_params.tsv**
```
Annotation      min_samps_gene_expr     min_samps_feature_expr  min_gene_expr   min_feature_expr
/home/weir/output/Nanopore-DGE-Analysis/Araport11_GFF3_genes_transposons.gtf    3       1       10      3
```
And,which Salmon library  should be used?
（Another question about "pandas" has been solved,THKS : )

**Comment by bsipos** [comment] 2019-03-06 09:58
Hello,

I do not know what could be the cause of this error. Would it be possible to upload the whole "merged/all_counts.tsv" somewhere?

Botond

**Comment by weir12** [comment] 2019-03-11 03:34
Hi,I guess the problem caused by this function：
https://github.com/nanoporetech/pipeline-transcriptome-de/blob/442923c1887c9f647dc685dc527d4ff569da3291/scripts/de_analysis.R#L22

the structure of my input raw `rownames(cts)` is similar to : **AT1G67090.2**  
After running this step ` rownames(cts) <- strip_version(rownames(cts))`
the new` rownames(cts)` is similar to **AT1G67090**
But` txdf$TXNAME` is similar to **AT1G67090.2**  
Thus,`txdf <- txdf[match(rownames(cts), txdf$TXNAME), ]` will would return a null set。
So I commented this line of code.The program no longer reports an error.
I don't know the rationality of this code change.Can you give me a hand?

**Comment by bsipos** [comment] 2019-03-11 10:46
The version numbers were removed because of the limitations of earlier versions of the stageR package. I believe the current version installed from bioconda should be fine with doing that. So indeed you can safely comment that line of code out.

Botond

**Closed as completed** 2019-03-11 10:46 UTC

**Comment by twincacca** [comment] 2021-01-28 06:54
Hello,

seems the problem is sometimes resistant to the solution of outcommenting "rownames(cts) <- strip_version(rownames(cts))". 

I still get the error

############################
Make the TxDb object ... OK
'select()' returned 1:1 mapping between keys and columns
Filtering counts using DRIMSeq.
Error in dmDSdata(counts = counts, samples = coldata) :
  mode(counts) %in% "numeric" is not TRUE
Calls: dmDSdata -> stopifnot
############################

when dealing with the transcriptome/annotation of at least two bacteria: 

1. Bacterium 1
[ftp://ftp.ensemblgenomes.org/pub/bacteria/release-49/fasta/bacteria_45_collection/candidatus_thiodictyon_syntrophicum_gca_002813775/cdna/Candidatus_thiodictyon_syntrophicum_gca_002813775.ASM281377v1.cdna.all.fa.gz](url)
[ftp://ftp.ensemblgenomes.org/pub/bacteria/release-49/gff3/bacteria_45_collection/candidatus_thiodictyon_syntrophicum_gca_002813775/Candidatus_thiodictyon_syntrophicum_gca_002813775.ASM281377v1.49.gff3.gz](url)

2. Bacterium 2
[ftp://ftp.ensemblgenomes.org/pub/bacteria/release-49/fasta/bacteria_10_collection/chlorobium_phaeobacteroides_dsm_266_gca_000015125/cdna/Chlorobium_phaeobacteroides_dsm_266_gca_000015125.ASM1512v1.cdna.all.fa.gz](url)
[ftp://ftp.ensemblgenomes.org/pub/bacteria/release-49/gff3/bacteria_10_collection/chlorobium_phaeobacteroides_dsm_266_gca_000015125/Chlorobium_phaeobacteroides_dsm_266_gca_000015125.ASM1512v1.49.gff3.gz
](url)

Of note: 
1. This was generated by running the pipeline-transcriptome-de with snakemake on a linux server, not in EPI2ME Labs. 
2. Running the very same thing with human transcriptome/annotation/data did not raise the problem.
3. The output /merged/all_counts.tsv is created successfully (i.e., it gets stuck at the DRIMSeq step in pipeline-transcriptome-de/script/de_analysis.R, probably not very useful step with bacteria).

Thanks!

Cheers,
Antoine

**Comment by weir12** [comment] 2021-01-28 09:16
> Hello,
> 
> seems the problem is sometimes resistant to the solution of outcommenting "rownames(cts) <- strip_version(rownames(cts))".
> 
> I still get the error
> 
> ############################
> Make the TxDb object ... OK
> 'select()' returned 1:1 mapping between keys and columns
> Filtering counts using DRIMSeq.
> Error in dmDSdata(counts = counts, samples = coldata) :
> mode(counts) %in% "numeric" is not TRUE
> Calls: dmDSdata -> stopifnot
> ############################
> 
> when dealing with the transcriptome/annotation of at least two bacteria:
> 
> 1. Bacterium 1
>    [ftp://ftp.ensemblgenomes.org/pub/bacteria/release-49/fasta/bacteria_45_collection/candidatus_thiodictyon_syntrophicum_gca_002813775/cdna/Candidatus_thiodictyon_syntrophicum_gca_002813775.ASM281377v1.cdna.all.fa.gz](url)
>    [ftp://ftp.ensemblgenomes.org/pub/bacteria/release-49/gff3/bacteria_45_collection/candidatus_thiodictyon_syntrophicum_gca_002813775/Candidatus_thiodictyon_syntrophicum_gca_002813775.ASM281377v1.49.gff3.gz](url)
> 2. Bacterium 2
>    [ftp://ftp.ensemblgenomes.org/pub/bacteria/release-49/fasta/bacteria_10_collection/chlorobium_phaeobacteroides_dsm_266_gca_000015125/cdna/Chlorobium_phaeobacteroides_dsm_266_gca_000015125.ASM1512v1.cdna.all.fa.gz](url)
>    [ftp://ftp.ensemblgenomes.org/pub/bacteria/release-49/gff3/bacteria_10_collection/chlorobium_phaeobacteroides_dsm_266_gca_000015125/Chlorobium_phaeobacteroides_dsm_266_gca_000015125.ASM1512v1.49.gff3.gz
>    ](url)
> 
> Of note:
> 
> 1. This was generated by running the pipeline-transcriptome-de with snakemake on a linux server, not in EPI2ME Labs.
> 2. Running the very same thing with human transcriptome/annotation/data did not raise the problem.
> 3. The output /merged/all_counts.tsv is created successfully (i.e., it gets stuck at the DRIMSeq step in pipeline-transcriptome-de/script/de_analysis.R, probably not very useful step with bacteria).
> 
> Thanks!
> 
> Cheers,
> Antoine

I haven't used this pipeline(including R language) for a long time, but I recommend that you use  debug syntax of R to check variable types and values in key steps
Good luck
